### ISSUE TITLE
yandex-disk gem

### ISSUE THREAD

**Issue by ev42** [hasanovbatyr/yandex-checker#1]
не сыроват ли?
    $ irb -r yandex/disk
    irb(main):001:0> cl=Yandex::Disk::Client.new(login: 'pimensolovyev@yandex.ru', password: 'cbjqnzredyov')
        => #<Yandex::Disk::Client:0x000000021a4b2>
    irb(main):002:0> cl.list '/'
        NameError: uninitialized constant Yandex::Disk::Client::Request::List::ListParser::DateTime
	    from /var/lib/gems/2.1.0/gems/yandex-disk-0.0.7/lib/yandex/disk/client/request/list.rb:77:in `characters'
           from /var/lib/gems/2.1.0/gems/nokogiri-1.6.4.1/lib/nokogiri/xml/sax/parser.rb:112:in `parse_with'

лечится require 'date'
но сомнительный осадочек остался(

**Comment by hasanovbatyr** [comment]
Сырой, ага.
Много методов вообще не работают,
